---

- name: Install efs dependencies
  yum:
    name: "{{ packages }}"
    state: latest
  vars: 
    packages:
    - amazon-efs-utils

- name: Create efs mountpint
  file:
    path: /mnt/efs
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0770'

#- name: Mount efs
#  mount:
#    src: "fs-dbe70e5a.efs.us-east-1.amazonaws.com:/"
#    path: "/mnt/efs"
#    fstype: nfs4
#    opts: nfsvers=4.1
#    #state: mounted
#    state: present 
#    #fstype: efs 
#    #opts: defaults,_netdev
#    #dump: 0
#    #passno: 0

# ISSUE - mount module on ami2 is not creating a newline before adding this line
- name: Add line to fstab
  lineinfile:
    path: /etc/fstab
    line: "fs-dbe70e5a:/ /mnt/efs efs defaults,_netdev 0 0"

# ISSUE - can't use mount here either because it loses a newline
- name: Mount efs
  command:
    cmd: "mount -a" 
    warn: false

# symlink efs to ec2-user home
# this step can be skipped
